### ISSUE TITLE
Crop Bounding Boxes after detection method extraction

### ISSUE THREAD

**Issue by tand826** [tand826/wsiprocess#21]
# Now
- do nothing after detection method extraction

**Comment by tand826** [comment]
The post-process of "detection" method should be in charge of cropping bounding box. I implemented this switch as "-cb" or "--crop_bbox" argument which is only available when you set "detection" method. Please beware of the bounding boxes on the border of each patch because they are split into some pieces, and not necessarily have the nuclei. wsiprocess saves these "mini patches" to "mini_patches" directory.

**Comment by bnapora** [comment]
Tested and Works
-the "mini patches" solution works for truncated bboxes.  I'm working on away to process them.

**Comment by tand826** [comment]
Thank you for testing!
