### ISSUE TITLE
basic_usage.py No any result

### ISSUE THREAD

**Issue by Gaodelike** [tand826/wsiprocess#45]
Hi author:
Thanks for your code！
I ran this script and found that only the folder is generated, but there is no tiles output in it, is my usage wrong or some other reason? 

Hope to get your reply。

Bests

**Comment by Gaodelike** [comment]
The benign and malignant folders are empty

**Comment by andolpixel** [comment]
@Gaodelike Thank you for the comment. It seems to be because "on_annotation" argument is too large. I updated the code with "on_annotation=0.1". Can you please run it again with the new code?

**Comment by tand826** [comment]
@Gaodelike
Thank you for the comment. It seems to be because the code uses too large "on_annotation" parameter although not more than 50% (default value) of the patch area is on the annotated area. The new code sets 10% for the parameter. Can you please run the code again?

**Comment by Gaodelike** [comment]
Awesome！
It ran out successfully.
I have another question:
My current annotation file doesn't seem to belong to any kind of annotation format, I may need to use custom annotation parser, but my annotation file seems to be missing some classification information, what do you suggest?
[14S02511-2.txt](https://github.com/tand826/wsiprocess/files/10879353/14S02511-2.txt)

**Comment by tand826** [comment]
@Gaodelike 
Great!
As you pointed out, the annotation file is not in any formats wsiprocess can handle now. With the code like below, you can parse the info of coordinations.

```
from lxml import etree
tree = etree.parse("14S02511-2.txt")
annotations = tree.xpath("/Annotations/Annotation/Regions/Region")
for annotation in annotations:
    for coord in annotation.xpath("Vertices/V"):
        print(coord.attrib["X"], coord.attrib["Y"])
```

But the label data is not clear. Is "NegativeROA" the label data? Is the annotation tool private one?

**Comment by Gaodelike** [comment]
This is the annotation data generated by HALO platform, which seems to be an uncommon annotation format. "NegativeROA" is not label information，HALO platform is paid for use, so it should be considered as a private annotation tool.As you can see, this type of annotation file lacks some label information. I may need to study it again. Anyway, thank you for your help!
Bests

**Comment by tand826** [comment]
I'm glad I could help. If you have further questions, feel free to reopen the issue.
Regards
