### ISSUE TITLE
Any guide to generate patches of images given a mask

### ISSUE THREAD

**Issue by bharaniabhishek123** [tand826/wsiprocess#7]
I am having .tiff for biopsy images and mask. Can we give mask images as an input to wsiprocess and extract patches where there is cancerous tissue ?

**Comment by tand826** [comment]
Thanks for the question.
I added `wsiprocess.annotation.Annotation.from_image()` for the image mask which is loaded with opencv-python. Code below is an example of the process, and you can also refer to the README.
This is not fully tested but should work fine. Please try after upgrading wsiprocess to 0.3.

```
import wsiprocess as wp
import cv2
slide = wp.slide("xxx.tiff")

annotation = wp.annotation("yyy.tiff", is_image=True)
target_classes = ["benign", "malignant"]
annotation.add_class(target_classes)
benign_mask = cv2.imread("benign_mask.png", 0)*255
malignant_mask = cv2.imread("malignant_mask.png", 0)*255
# Make sure your mask data includes only 0 as background or 255 as foreground
annotation.from_image(benign_mask, "benign")
annotation.from_image(malignant_mask, "malignant")

rule = wp.rule("xxx.json")
patcher = wp.patcher(slide, "classification", annotation)
patcher.get_patch_parallel(target_classes)
```
