### ISSUE TITLE
ModuleNotFoundError: No module named 'wsiprocess.converters'

### ISSUE THREAD

**Issue by Arghya999** [tand826/wsiprocess#8]
"import wsiprocess as wp"    generates:- 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-5ff22b5ff7b1> in <module>
----> 1 import wsiprocess as wp

~/.conda/envs/digital_pathology_conda/lib/python3.6/site-packages/wsiprocess/__init__.py in <module>
      3 from .annotation import Annotation as annotation
      4 from .rule import Rule as rule
----> 5 from .converter import Converter as converter
      6 
      7 __version__ = 0.3

~/.conda/envs/digital_pathology_conda/lib/python3.6/site-packages/wsiprocess/converter.py in <module>
      2 """Convert wsiprocess style annotation data to COCO or VOC style.
      3 """
----> 4 from .converters import (
      5     wsiprocess_to_coco,
      6     wsiprocess_to_voc,

ModuleNotFoundError: No module named 'wsiprocess.converters'

**Comment by tand826** [comment]
Thanks for the comment.

Please do
`pip install wsiprocess==0.3.1`
I fixed "package" of setup.cfg and latest version wsiprocess==0.3.1 would not give the error.
